### PR TITLE
Fix: long lines and unnecessary scroll in `code`

### LINKED ISSUE #72: Scrolling

### LINKED ISSUE #73: Very long lines in the code view doesn't seem to respect the content width
Originally reported by Kyle Goertz

### PR DESCRIPTION
**Pull request by andreystepanov**
- Fixes #72 
- Fixes #73

### CODE REVIEW

**Comment by andreystepanov** [comment]
To not limit wrapping of long lines only to literals (like `bytes`, `text` etc.) and make it more universal by applying styles on `code .syntax`.

I don't know where else `code` is used, so decided to apply styles only to `span.syntax` inside `code`. `.syntax` is added dynamically only when block is opened and full definition is shown to the user.

So this shouldn't break anything else.

**Comment by andreystepanov** [comment]
Links to check before and after.

For #72:

https://share.unison-lang.org/@dfreeman/tvGuide/code/main/latest/terms/wordle/ui/applyInputToGameState

For #73:

https://share.unison-lang.org/@rlmark/cloudDoodles/code/releases/1.0.0/latest/terms/assets/indexHtml

**Comment by hojberg** [comment]
Hmmm I'm not sure wrapping is the right solution. A horizontal scrollbar inside the code block is the "more true to the syntax rendering" way. I feel like I've fixed that like 5 times only for it to show up in a different form 😭

**Comment by hojberg** [comment]
Thanks for looking into this @andreystepanov. I just merged #86 which fixes this without doing wrapping on the code.

**Pull request closed without merging**
